version: "3"
services:
  parade:
    image: paradedb/paradedb:0.5.7
    container_name: parade
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=dev
    ports:
      - 2345:5432
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    command:
      - "postgres"
      - "-c"
      - "max_connections=1024"
